
server.port: ${SERVER_PORT:8081}
 
#################
# GENERAL
#################

spring:
  application: 
    name: desafiojava
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:334863333}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true     # Enables SQL formatting
    show-sql: true           # Shows SQL statements in the console
    format-sql: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      hibernate:
        type: trace
   
server:
  servlet:
    session:
      cookie: 
        same-site:
          lax

  